language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install pkg-config autoconf automake libtool texinfo sed make python-pip debhelper check
install: pip install pytest==2.9.2 requests==2.18.1
script: ./autogen.sh && ./configure && make && make check && py.test integ/
